### Configurations

In [1]:
import pandas as pd
from players import *
from simulator import simulate_game

In [2]:
player1_list = [RandomPlayer(), NicePlayer(), GreedyPlayer(), FicklePlayer(), GrudgePlayer(), \
                CopycatPlayer(), SoreLoserPlayer(), CautiousPlayer(), CopykittenPlayer(), StrategicPlayer()]
player2_list = [RandomPlayer(), NicePlayer(), GreedyPlayer(), FicklePlayer(), GrudgePlayer(), \
                CopycatPlayer(), SoreLoserPlayer(), CautiousPlayer(), CopykittenPlayer(), StrategicPlayer()]

no_games = 100
pot = 1000
pool = 100
max_round = 10

In [3]:
def get_df_report(no_games):
    dict_list = []
    for player1 in player1_list:
        for player2 in player2_list:
            dict_list.append(get_results(player1, player2, no_games))
    return pd.DataFrame.from_dict(dict_list)


def get_player_matchup(df, player):
    print("Most earning against")
    display(get_matchup(df, player))
    print()
    print("Least earning against")
    display(get_matchup(df, player, advantage=-1))
    print()
    print("Most advantage against")
    display(get_matchup(df, player, metric='DifferenceMoney'))
    print()
    print("Most fair against")
    display(get_matchup(df, player, metric='DifferenceMoney', advantage=0))
    print()
    print("Least advantage against")
    display(get_matchup(df, player, metric='DifferenceMoney', advantage=-1))


def get_metric_matchup(df, metric, advantage):
    df_temp = pd.DataFrame(columns=['Player', 'Opponent', 'Win', 'Draw', 'Lose', 'PlayerMoney', 'OpponentMoney', \
                                    'DifferenceMoney'])
    for player1 in player1_list:
        df_temp = df_temp.append(get_matchup(df, player1.get_class(), metric, advantage), ignore_index=True)
    return df_temp
    

def get_results(player1, player2, no_games):
    results = {'Player': player1.get_class(), 'Opponent': player2.get_class(), 'Win': 0, 'Draw': 0, 'Lose': 0, \
               'PlayerMoney': 0, 'OpponentMoney': 0}
    for i in range(no_games):
        simulate_game(player1, player2, pot, pool, max_round)
        if player1.money == player2.money:
            results['Draw'] += 1
        elif player1.money > player2.money:
            results['Win'] += 1
        else:
            results['Lose'] += 1
        results['PlayerMoney'] += player1.money
        results['OpponentMoney'] += player2.money
    results['PlayerMoney'] /= no_games
    results['OpponentMoney'] /= no_games
    return results


def get_matchup(df, player, metric='PlayerMoney', advantage=1):
    dict_list = []
    df_temp = df.loc[df['Player'] == player]
    if advantage == 1:
        match = df_temp.loc[df_temp[metric] == df_temp[metric].max()].to_dict('records')
    elif advantage == 0:
        match = df_temp.loc[abs(df_temp[metric]) == abs(df_temp[metric]).min()].to_dict('records')
    else:
        match = df_temp.loc[df_temp[metric] == df_temp[metric].min()].to_dict('records')
    dict_list += match

    return pd.DataFrame.from_dict(dict_list)

### Simulate game

In [4]:
df = get_df_report(no_games)
df['DifferenceMoney'] = df['PlayerMoney'] - df['OpponentMoney']
df.head()

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,RandomPlayer,46,17,37,390.5,366.5,24.0
1,RandomPlayer,NicePlayer,99,1,0,752.0,248.0,504.0
2,RandomPlayer,GreedyPlayer,0,0,100,0.0,513.0,-513.0
3,RandomPlayer,FicklePlayer,38,20,42,370.0,386.0,-16.0
4,RandomPlayer,GrudgePlayer,1,4,95,144.5,442.5,-298.0

### Result

In [5]:
for player in player1_list:
    display(df.loc[df['Player'] == player.get_class()])
    print()

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,RandomPlayer,46,17,37,390.5,366.5,24.0
1,RandomPlayer,NicePlayer,99,1,0,752.0,248.0,504.0
2,RandomPlayer,GreedyPlayer,0,0,100,0.0,513.0,-513.0
3,RandomPlayer,FicklePlayer,38,20,42,370.0,386.0,-16.0
4,RandomPlayer,GrudgePlayer,1,4,95,144.5,442.5,-298.0
5,RandomPlayer,CopycatPlayer,45,55,0,399.5,354.5,45.0
6,RandomPlayer,SoreLoserPlayer,54,46,0,417.0,363.0,54.0
7,RandomPlayer,CautiousPlayer,0,14,86,257.0,403.0,-146.0
8,RandomPlayer,CopykittenPlayer,51,49,0,418.0,366.0,52.0
9,RandomPlayer,StrategicPlayer,65,29,6,441.0,347.0,94.0

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
10,NicePlayer,RandomPlayer,0,1,99,254.5,745.5,-491.0
11,NicePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
12,NicePlayer,GreedyPlayer,0,0,100,0.0,1000.0,-1000.0
13,NicePlayer,FicklePlayer,0,0,100,250.0,750.0,-500.0
14,NicePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
15,NicePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
16,NicePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
17,NicePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
18,NicePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
19,NicePlayer,StrategicPlayer,0,0,100,150.0,850.0,-700.0

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
20,GreedyPlayer,RandomPlayer,100,0,0,497.0,0.0,497.0
21,GreedyPlayer,NicePlayer,100,0,0,1000.0,0.0,1000.0
22,GreedyPlayer,GreedyPlayer,0,100,0,0.0,0.0,0.0
23,GreedyPlayer,FicklePlayer,100,0,0,500.0,0.0,500.0
24,GreedyPlayer,GrudgePlayer,100,0,0,100.0,0.0,100.0
25,GreedyPlayer,CopycatPlayer,100,0,0,100.0,0.0,100.0
26,GreedyPlayer,SoreLoserPlayer,100,0,0,100.0,0.0,100.0
27,GreedyPlayer,CautiousPlayer,100,0,0,100.0,0.0,100.0
28,GreedyPlayer,CopykittenPlayer,100,0,0,100.0,0.0,100.0
29,GreedyPlayer,StrategicPlayer,100,0,0,300.0,0.0,300.0

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
30,FicklePlayer,RandomPlayer,36,29,35,380.5,376.5,4.0
31,FicklePlayer,NicePlayer,100,0,0,750.0,250.0,500.0
32,FicklePlayer,GreedyPlayer,0,0,100,0.0,500.0,-500.0
33,FicklePlayer,FicklePlayer,0,100,0,362.5,362.5,0.0
34,FicklePlayer,GrudgePlayer,0,0,100,123.5,476.5,-353.0
35,FicklePlayer,CopycatPlayer,49,51,0,524.5,475.5,49.0
36,FicklePlayer,SoreLoserPlayer,54,46,0,527.0,473.0,54.0
37,FicklePlayer,CautiousPlayer,0,0,100,125.5,474.5,-349.0
38,FicklePlayer,CopykittenPlayer,47,53,0,523.5,476.5,47.0
39,FicklePlayer,StrategicPlayer,100,0,0,525.5,425.5,100.0

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
40,GrudgePlayer,RandomPlayer,96,4,0,437.0,136.0,301.0
41,GrudgePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
42,GrudgePlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
43,GrudgePlayer,FicklePlayer,100,0,0,481.0,119.0,362.0
44,GrudgePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
45,GrudgePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
46,GrudgePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
47,GrudgePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
48,GrudgePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
49,GrudgePlayer,StrategicPlayer,100,0,0,250.0,150.0,100.0

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
50,CopycatPlayer,RandomPlayer,0,48,52,359.5,411.5,-52.0
51,CopycatPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
52,CopycatPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
53,CopycatPlayer,FicklePlayer,0,53,47,476.5,523.5,-47.0
54,CopycatPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
55,CopycatPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
56,CopycatPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
57,CopycatPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
58,CopycatPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
59,CopycatPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
60,SoreLoserPlayer,RandomPlayer,0,48,52,359.0,411.0,-52.0
61,SoreLoserPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
62,SoreLoserPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
63,SoreLoserPlayer,FicklePlayer,0,41,59,470.5,529.5,-59.0
64,SoreLoserPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
65,SoreLoserPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
66,SoreLoserPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
67,SoreLoserPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
68,SoreLoserPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
69,SoreLoserPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
70,CautiousPlayer,RandomPlayer,87,12,1,391.5,247.5,144.0
71,CautiousPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
72,CautiousPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
73,CautiousPlayer,FicklePlayer,100,0,0,475.5,124.5,351.0
74,CautiousPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
75,CautiousPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
76,CautiousPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
77,CautiousPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
78,CautiousPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
79,CautiousPlayer,StrategicPlayer,100,0,0,350.0,250.0,100.0

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
80,CopykittenPlayer,RandomPlayer,0,44,56,365.5,421.5,-56.0
81,CopykittenPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
82,CopykittenPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
83,CopykittenPlayer,FicklePlayer,0,51,49,475.5,524.5,-49.0
84,CopykittenPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
85,CopykittenPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
86,CopykittenPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
87,CopykittenPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
88,CopykittenPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
89,CopykittenPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
90,StrategicPlayer,RandomPlayer,5,30,65,343.5,442.5,-99.0
91,StrategicPlayer,NicePlayer,100,0,0,850.0,150.0,700.0
92,StrategicPlayer,GreedyPlayer,0,0,100,0.0,300.0,-300.0
93,StrategicPlayer,FicklePlayer,0,0,100,430.0,530.0,-100.0
94,StrategicPlayer,GrudgePlayer,0,0,100,150.0,250.0,-100.0
95,StrategicPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
96,StrategicPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
97,StrategicPlayer,CautiousPlayer,0,0,100,250.0,350.0,-100.0
98,StrategicPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
99,StrategicPlayer,StrategicPlayer,0,100,0,450.0,450.0,0.0

### Average

In [6]:
# Win
df.groupby('Player').mean().sort_values(by=['Win'], ascending=False)

,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
Player,,,,,,
GreedyPlayer,90.0,10.0,0.0,279.70,0.00,279.7
RandomPlayer,39.9,23.5,36.6,358.95,378.95,-20.0
FicklePlayer,38.6,27.9,33.5,384.25,429.05,-44.8
GrudgePlayer,29.6,60.4,10.0,416.80,350.50,66.3
CautiousPlayer,28.7,61.2,10.1,421.70,372.20,49.5
StrategicPlayer,10.5,43.0,46.5,397.35,397.25,0.1
CopycatPlayer,0.0,80.1,19.9,433.60,453.50,-19.9
CopykittenPlayer,0.0,79.5,20.5,434.10,454.60,-20.5
NicePlayer,0.0,60.1,39.9,365.45,634.55,-269.1
SoreLoserPlayer,0.0,78.9,21.1,432.95,454.05,-21.1

In [7]:
# Draw
df.groupby('Player').mean().sort_values(by=['Draw'], ascending=False)

,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
Player,,,,,,
CopycatPlayer,0.0,80.1,19.9,433.60,453.50,-19.9
CopykittenPlayer,0.0,79.5,20.5,434.10,454.60,-20.5
SoreLoserPlayer,0.0,78.9,21.1,432.95,454.05,-21.1
CautiousPlayer,28.7,61.2,10.1,421.70,372.20,49.5
GrudgePlayer,29.6,60.4,10.0,416.80,350.50,66.3
NicePlayer,0.0,60.1,39.9,365.45,634.55,-269.1
StrategicPlayer,10.5,43.0,46.5,397.35,397.25,0.1
FicklePlayer,38.6,27.9,33.5,384.25,429.05,-44.8
RandomPlayer,39.9,23.5,36.6,358.95,378.95,-20.0
GreedyPlayer,90.0,10.0,0.0,279.70,0.00,279.7

In [8]:
# Lose
df.groupby('Player').mean().sort_values(by=['Lose'], ascending=False)

,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
Player,,,,,,
StrategicPlayer,10.5,43.0,46.5,397.35,397.25,0.1
NicePlayer,0.0,60.1,39.9,365.45,634.55,-269.1
RandomPlayer,39.9,23.5,36.6,358.95,378.95,-20.0
FicklePlayer,38.6,27.9,33.5,384.25,429.05,-44.8
SoreLoserPlayer,0.0,78.9,21.1,432.95,454.05,-21.1
CopykittenPlayer,0.0,79.5,20.5,434.10,454.60,-20.5
CopycatPlayer,0.0,80.1,19.9,433.60,453.50,-19.9
CautiousPlayer,28.7,61.2,10.1,421.70,372.20,49.5
GrudgePlayer,29.6,60.4,10.0,416.80,350.50,66.3
GreedyPlayer,90.0,10.0,0.0,279.70,0.00,279.7

In [9]:
# Player money
df.groupby('Player').mean().sort_values(by=['PlayerMoney'], ascending=False)

,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
Player,,,,,,
CopykittenPlayer,0.0,79.5,20.5,434.10,454.60,-20.5
CopycatPlayer,0.0,80.1,19.9,433.60,453.50,-19.9
SoreLoserPlayer,0.0,78.9,21.1,432.95,454.05,-21.1
CautiousPlayer,28.7,61.2,10.1,421.70,372.20,49.5
GrudgePlayer,29.6,60.4,10.0,416.80,350.50,66.3
StrategicPlayer,10.5,43.0,46.5,397.35,397.25,0.1
FicklePlayer,38.6,27.9,33.5,384.25,429.05,-44.8
NicePlayer,0.0,60.1,39.9,365.45,634.55,-269.1
RandomPlayer,39.9,23.5,36.6,358.95,378.95,-20.0
GreedyPlayer,90.0,10.0,0.0,279.70,0.00,279.7

In [10]:
# Opponent money
df.groupby('Player').mean().sort_values(by=['OpponentMoney'], ascending=False)

,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
Player,,,,,,
NicePlayer,0.0,60.1,39.9,365.45,634.55,-269.1
CopykittenPlayer,0.0,79.5,20.5,434.10,454.60,-20.5
SoreLoserPlayer,0.0,78.9,21.1,432.95,454.05,-21.1
CopycatPlayer,0.0,80.1,19.9,433.60,453.50,-19.9
FicklePlayer,38.6,27.9,33.5,384.25,429.05,-44.8
StrategicPlayer,10.5,43.0,46.5,397.35,397.25,0.1
RandomPlayer,39.9,23.5,36.6,358.95,378.95,-20.0
CautiousPlayer,28.7,61.2,10.1,421.70,372.20,49.5
GrudgePlayer,29.6,60.4,10.0,416.80,350.50,66.3
GreedyPlayer,90.0,10.0,0.0,279.70,0.00,279.7

In [11]:
# Difference in player money and opponent money
df.groupby('Player').mean().sort_values(by=['DifferenceMoney'], ascending=False)

,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
Player,,,,,,
GreedyPlayer,90.0,10.0,0.0,279.70,0.00,279.7
GrudgePlayer,29.6,60.4,10.0,416.80,350.50,66.3
CautiousPlayer,28.7,61.2,10.1,421.70,372.20,49.5
StrategicPlayer,10.5,43.0,46.5,397.35,397.25,0.1
CopycatPlayer,0.0,80.1,19.9,433.60,453.50,-19.9
RandomPlayer,39.9,23.5,36.6,358.95,378.95,-20.0
CopykittenPlayer,0.0,79.5,20.5,434.10,454.60,-20.5
SoreLoserPlayer,0.0,78.9,21.1,432.95,454.05,-21.1
FicklePlayer,38.6,27.9,33.5,384.25,429.05,-44.8
NicePlayer,0.0,60.1,39.9,365.45,634.55,-269.1

### Player match up

In [12]:
get_player_matchup(df, 'RandomPlayer')

Most earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,NicePlayer,99,1,0,752.0,248.0,504.0

Least earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,GreedyPlayer,0,0,100,0.0,513.0,-513.0

Most advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,NicePlayer,99,1,0,752.0,248.0,504.0

Most fair against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,FicklePlayer,38,20,42,370.0,386.0,-16.0

Least advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,GreedyPlayer,0,0,100,0.0,513.0,-513.0

In [13]:
get_player_matchup(df, 'NicePlayer')

Most earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,NicePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,NicePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,NicePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,NicePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,NicePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,NicePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0

Least earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,NicePlayer,GreedyPlayer,0,0,100,0.0,1000.0,-1000.0

Most advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,NicePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,NicePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,NicePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,NicePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,NicePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,NicePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0

Most fair against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,NicePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,NicePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,NicePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,NicePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,NicePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,NicePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0

Least advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,NicePlayer,GreedyPlayer,0,0,100,0.0,1000.0,-1000.0

In [14]:
get_player_matchup(df, 'GreedyPlayer')

Most earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,GreedyPlayer,NicePlayer,100,0,0,1000.0,0.0,1000.0

Least earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,GreedyPlayer,GreedyPlayer,0,100,0,0.0,0.0,0.0

Most advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,GreedyPlayer,NicePlayer,100,0,0,1000.0,0.0,1000.0

Most fair against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,GreedyPlayer,GreedyPlayer,0,100,0,0.0,0.0,0.0

Least advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,GreedyPlayer,GreedyPlayer,0,100,0,0.0,0.0,0.0

In [15]:
get_player_matchup(df, 'FicklePlayer')

Most earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,FicklePlayer,NicePlayer,100,0,0,750.0,250.0,500.0

Least earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,FicklePlayer,GreedyPlayer,0,0,100,0.0,500.0,-500.0

Most advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,FicklePlayer,NicePlayer,100,0,0,750.0,250.0,500.0

Most fair against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,FicklePlayer,FicklePlayer,0,100,0,362.5,362.5,0.0

Least advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,FicklePlayer,GreedyPlayer,0,0,100,0.0,500.0,-500.0

In [16]:
get_player_matchup(df, 'GrudgePlayer')

Most earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,GrudgePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,GrudgePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,GrudgePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,GrudgePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,GrudgePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,GrudgePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0

Least earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,GrudgePlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0

Most advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,GrudgePlayer,FicklePlayer,100,0,0,481.0,119.0,362.0

Most fair against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,GrudgePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,GrudgePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,GrudgePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,GrudgePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,GrudgePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,GrudgePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0

Least advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,GrudgePlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0

In [17]:
get_player_matchup(df, 'CopycatPlayer')

Most earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CopycatPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,CopycatPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,CopycatPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,CopycatPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,CopycatPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,CopycatPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
6,CopycatPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

Least earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CopycatPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0

Most advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CopycatPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,CopycatPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,CopycatPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,CopycatPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,CopycatPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,CopycatPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
6,CopycatPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

Most fair against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CopycatPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,CopycatPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,CopycatPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,CopycatPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,CopycatPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,CopycatPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
6,CopycatPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

Least advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CopycatPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0

In [18]:
get_player_matchup(df, 'SoreLoserPlayer')

Most earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,SoreLoserPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,SoreLoserPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,SoreLoserPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,SoreLoserPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,SoreLoserPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,SoreLoserPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
6,SoreLoserPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

Least earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,SoreLoserPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0

Most advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,SoreLoserPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,SoreLoserPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,SoreLoserPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,SoreLoserPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,SoreLoserPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,SoreLoserPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
6,SoreLoserPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

Most fair against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,SoreLoserPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,SoreLoserPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,SoreLoserPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,SoreLoserPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,SoreLoserPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,SoreLoserPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
6,SoreLoserPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

Least advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,SoreLoserPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0

In [19]:
get_player_matchup(df, 'CautiousPlayer')

Most earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CautiousPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,CautiousPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,CautiousPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,CautiousPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,CautiousPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,CautiousPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0

Least earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CautiousPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0

Most advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CautiousPlayer,FicklePlayer,100,0,0,475.5,124.5,351.0

Most fair against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CautiousPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,CautiousPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,CautiousPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,CautiousPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,CautiousPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,CautiousPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0

Least advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CautiousPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0

In [20]:
get_player_matchup(df, 'CopykittenPlayer')

Most earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CopykittenPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,CopykittenPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,CopykittenPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,CopykittenPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,CopykittenPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,CopykittenPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
6,CopykittenPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

Least earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CopykittenPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0

Most advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CopykittenPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,CopykittenPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,CopykittenPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,CopykittenPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,CopykittenPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,CopykittenPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
6,CopykittenPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

Most fair against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CopykittenPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
1,CopykittenPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
2,CopykittenPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
3,CopykittenPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
4,CopykittenPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
5,CopykittenPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
6,CopykittenPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0

Least advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,CopykittenPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0

In [21]:
get_player_matchup(df, 'StrategicPlayer')

Most earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,StrategicPlayer,NicePlayer,100,0,0,850.0,150.0,700.0

Least earning against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,StrategicPlayer,GreedyPlayer,0,0,100,0.0,300.0,-300.0

Most advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,StrategicPlayer,NicePlayer,100,0,0,850.0,150.0,700.0

Most fair against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,StrategicPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
1,StrategicPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
2,StrategicPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
3,StrategicPlayer,StrategicPlayer,0,100,0,450.0,450.0,0.0

Least advantage against

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,StrategicPlayer,GreedyPlayer,0,0,100,0.0,300.0,-300.0

### Metric match up

Most earning against

In [22]:
most_earning = get_metric_matchup(df, 'PlayerMoney', 1)
most_earning

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,NicePlayer,99,1,0,752.0,248.0,504.0
1,NicePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
2,NicePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
3,NicePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
4,NicePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
5,NicePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
6,NicePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
7,GreedyPlayer,NicePlayer,100,0,0,1000.0,0.0,1000.0
8,FicklePlayer,NicePlayer,100,0,0,750.0,250.0,500.0
9,GrudgePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
10,GrudgePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
11,GrudgePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
12,GrudgePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
13,GrudgePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
14,GrudgePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
15,CopycatPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
16,CopycatPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
17,CopycatPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
18,CopycatPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
19,CopycatPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
20,CopycatPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
21,CopycatPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0
22,SoreLoserPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
23,SoreLoserPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
24,SoreLoserPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
25,SoreLoserPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
26,SoreLoserPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
27,SoreLoserPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
28,SoreLoserPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0
29,CautiousPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
30,CautiousPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
31,CautiousPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
32,CautiousPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
33,CautiousPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
34,CautiousPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
35,CopykittenPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
36,CopykittenPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
37,CopykittenPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
38,CopykittenPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
39,CopykittenPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
40,CopykittenPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
41,CopykittenPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0
42,StrategicPlayer,NicePlayer,100,0,0,850.0,150.0,700.0

In [23]:
most_earning['Opponent'].value_counts()

NicePlayer          10
CopykittenPlayer     6
CautiousPlayer       6
GrudgePlayer         6
CopycatPlayer        6
SoreLoserPlayer      6
StrategicPlayer      3
Name: Opponent, dtype: int64

Least earning against

In [24]:
least_earning = get_metric_matchup(df, 'PlayerMoney', -1)
least_earning

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,GreedyPlayer,0,0,100,0.0,513.0,-513.0
1,NicePlayer,GreedyPlayer,0,0,100,0.0,1000.0,-1000.0
2,GreedyPlayer,GreedyPlayer,0,100,0,0.0,0.0,0.0
3,FicklePlayer,GreedyPlayer,0,0,100,0.0,500.0,-500.0
4,GrudgePlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
5,CopycatPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
6,SoreLoserPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
7,CautiousPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
8,CopykittenPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
9,StrategicPlayer,GreedyPlayer,0,0,100,0.0,300.0,-300.0

In [25]:
least_earning['Opponent'].value_counts()

GreedyPlayer    10
Name: Opponent, dtype: int64

Most advantage against

In [26]:
most_advantage = get_metric_matchup(df, 'DifferenceMoney', 1)
most_advantage

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,NicePlayer,99,1,0,752.0,248.0,504.0
1,NicePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
2,NicePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
3,NicePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
4,NicePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
5,NicePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
6,NicePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
7,GreedyPlayer,NicePlayer,100,0,0,1000.0,0.0,1000.0
8,FicklePlayer,NicePlayer,100,0,0,750.0,250.0,500.0
9,GrudgePlayer,FicklePlayer,100,0,0,481.0,119.0,362.0
10,CopycatPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
11,CopycatPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
12,CopycatPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
13,CopycatPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
14,CopycatPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
15,CopycatPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
16,CopycatPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0
17,SoreLoserPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
18,SoreLoserPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
19,SoreLoserPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
20,SoreLoserPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
21,SoreLoserPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
22,SoreLoserPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
23,SoreLoserPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0
24,CautiousPlayer,FicklePlayer,100,0,0,475.5,124.5,351.0
25,CopykittenPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
26,CopykittenPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
27,CopykittenPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
28,CopykittenPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
29,CopykittenPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
30,CopykittenPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
31,CopykittenPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0
32,StrategicPlayer,NicePlayer,100,0,0,850.0,150.0,700.0

In [27]:
most_advantage['Opponent'].value_counts()

NicePlayer          8
CopykittenPlayer    4
CautiousPlayer      4
GrudgePlayer        4
CopycatPlayer       4
SoreLoserPlayer     4
StrategicPlayer     3
FicklePlayer        2
Name: Opponent, dtype: int64

Most fair against

In [28]:
most_fair = get_metric_matchup(df, 'DifferenceMoney', 0)
most_fair

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,FicklePlayer,38,20,42,370.0,386.0,-16.0
1,NicePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
2,NicePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
3,NicePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
4,NicePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
5,NicePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
6,NicePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
7,GreedyPlayer,GreedyPlayer,0,100,0,0.0,0.0,0.0
8,FicklePlayer,FicklePlayer,0,100,0,362.5,362.5,0.0
9,GrudgePlayer,NicePlayer,0,100,0,500.0,500.0,0.0
10,GrudgePlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
11,GrudgePlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
12,GrudgePlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
13,GrudgePlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
14,GrudgePlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
15,CopycatPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
16,CopycatPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
17,CopycatPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
18,CopycatPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
19,CopycatPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
20,CopycatPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
21,CopycatPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0
22,SoreLoserPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
23,SoreLoserPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
24,SoreLoserPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
25,SoreLoserPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
26,SoreLoserPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
27,SoreLoserPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
28,SoreLoserPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0
29,CautiousPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
30,CautiousPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
31,CautiousPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
32,CautiousPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
33,CautiousPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
34,CautiousPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
35,CopykittenPlayer,NicePlayer,0,100,0,500.0,500.0,0.0
36,CopykittenPlayer,GrudgePlayer,0,100,0,500.0,500.0,0.0
37,CopykittenPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
38,CopykittenPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
39,CopykittenPlayer,CautiousPlayer,0,100,0,500.0,500.0,0.0
40,CopykittenPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
41,CopykittenPlayer,StrategicPlayer,0,100,0,500.0,500.0,0.0
42,StrategicPlayer,CopycatPlayer,0,100,0,500.0,500.0,0.0
43,StrategicPlayer,SoreLoserPlayer,0,100,0,500.0,500.0,0.0
44,StrategicPlayer,CopykittenPlayer,0,100,0,500.0,500.0,0.0
45,StrategicPlayer,StrategicPlayer,0,100,0,450.0,450.0,0.0

In [29]:
most_fair['Opponent'].value_counts()

CopykittenPlayer    7
CopycatPlayer       7
SoreLoserPlayer     7
NicePlayer          6
CautiousPlayer      6
GrudgePlayer        6
StrategicPlayer     4
FicklePlayer        2
GreedyPlayer        1
Name: Opponent, dtype: int64

Least advantage against

In [30]:
least_advantage = get_metric_matchup(df, 'DifferenceMoney', -1)
least_advantage

,Player,Opponent,Win,Draw,Lose,PlayerMoney,OpponentMoney,DifferenceMoney
0,RandomPlayer,GreedyPlayer,0,0,100,0.0,513.0,-513.0
1,NicePlayer,GreedyPlayer,0,0,100,0.0,1000.0,-1000.0
2,GreedyPlayer,GreedyPlayer,0,100,0,0.0,0.0,0.0
3,FicklePlayer,GreedyPlayer,0,0,100,0.0,500.0,-500.0
4,GrudgePlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
5,CopycatPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
6,SoreLoserPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
7,CautiousPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
8,CopykittenPlayer,GreedyPlayer,0,0,100,0.0,100.0,-100.0
9,StrategicPlayer,GreedyPlayer,0,0,100,0.0,300.0,-300.0

In [31]:
least_advantage['Opponent'].value_counts()

GreedyPlayer    10
Name: Opponent, dtype: int64